# Generated by Django 6.0.2 on 2026-02-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswerresult',
            name='selected_answers',
        ),
        migrations.AddField(
            model_name='questionanswerresult',
            name='selected_answers',
            field=models.ManyToManyField(to='testing.questionanswer'),
        ),
    ]
