# Generated by Django 6.0.1 on 2026-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='school_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
