# Generated by Django 6.0.2 on 2026-02-27 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_teacherprofile_school_name_and_more'),
        ('edu', '0003_alter_classsubject_school_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='homework',
        ),
        migrations.CreateModel(
            name='FileHomeWork',
            fields=[
                ('homework', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fileHomeWork', serialize=False, to='edu.homework')),
                ('text', models.CharField(blank=True)),
                ('file', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextHomeWork',
            fields=[
                ('homework', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='textHomeWork', serialize=False, to='edu.homework')),
                ('text', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='edu.lesson'),
        ),
        migrations.CreateModel(
            name='UserHomeWork',
            fields=[
                ('homework', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='edu.homework')),
                ('text', models.CharField(blank=True)),
                ('file', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DN', 'Проверено'), ('CH', 'На проверке'), ('WN', 'Ожидает проверки')], default='WN', max_length=3)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='accounts.userprofile')),
            ],
        ),
    ]
