# Generated by Django 6.0.2 on 2026-02-27 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_homework_remove_lesson_homework_filehomework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehomework',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fileHomeWork', serialize=False, to='edu.homework'),
        ),
        migrations.AlterField(
            model_name='texthomework',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='textHomeWork', serialize=False, to='edu.homework'),
        ),
    ]
