# Generated by Django 6.0.2 on 2026-03-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_teacherprofile_school_name_and_more'),
        ('edu', '0005_alter_filehomework_homework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhomework',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='edu.homework'),
        ),
        migrations.AlterField(
            model_name='userhomework',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='accounts.userprofile'),
        ),
    ]
