FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=config.settings.dev

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

COPY requirements.txt .
RUN pip install -r requirements.txt
# RUN pip install --no-cache -r requirements.txt

COPY docker/entrypoint_dev.sh /entrypoint_dev.sh
RUN chmod +x /entrypoint_dev.sh
