# Generated by Django 5.1.4 on 2026-02-12 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='edu.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student'], name='journal_att_student_b8b4f7_idx'), models.Index(fields=['lesson'], name='journal_att_lesson__a8a978_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='uniq_attendance_per_lesson')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_from', models.DateField(db_index=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['school_class', 'is_active'], name='journal_enr_school__f6b3a2_idx'), models.Index(fields=['student', 'is_active'], name='journal_enr_student_a57716_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'school_class', 'date_from'), name='uniq_enrollment_period')],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveSmallIntegerField()),
                ('grade_type', models.CharField(choices=[('lesson', 'Lesson'), ('exam', 'Exam'), ('homework', 'Homework')], default='lesson', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='edu.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student'], name='journal_gra_student_687387_idx'), models.Index(fields=['lesson'], name='journal_gra_lesson__96ba3f_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson', 'grade_type'), name='uniq_grade_per_lesson_type')],
            },
        ),
    ]
